Clean up the condor stuff so that it submits one monolithic job, and blocks until it's finished.

diff --git a/bin/condor b/bin/condor
--- a/bin/condor
+++ b/bin/condor
@@ -2,6 +2,15 @@
 #This script should be called from the folder: mln-semantic using the command bin/condor
 CMD=$1
 
+# full is just some shortcut
+if [ "$CMD" == "full" ]; then
+	shift
+	bash $0 "submit" $@
+	bash $0 "collect" $@
+	bash $0 "eval" $@
+	exit 0
+fi
+
 case $CMD in
 	status)
 		shift
@@ -21,19 +30,6 @@ if [ -z "$expDir" ]; then
 fi
 
 outputDir="$expDir/"
-
-#step=$3
-#if [ -z "$step" ] || [ "$step" -le "0" ]; then
-#	echo "step can not be zero or empty"
-#	exit 1
-#fi
-
-#total=$(( 5000+$step-1 ))
-#total=$(( $total / $step ))
-#echo "Number of jobs $total"
-#shift
-#shift
-#shift
 
 case $CMD in
 	submit | print)
@@ -99,13 +95,12 @@ case $CMD in
 		esac
 		total=$(( $dsSize+$step-1 ))
 		total=$(( $total / $step ))
-		echo "Number of jobs $total"
+		#echo "Number of jobs $total" >&2
 		shift #CMD
 		shift #outputDir
 		shift #step
 		shift #DS
 		args=" $DS -task $task $@"
-		echo "Storing condor output files in : $outputDir. Old content will be overwritten"
 		
 		if [ "$CMD" == "submit" ]; then
 			rm $outputDir -r
@@ -137,17 +132,13 @@ collectBuffer=""
 errorCnt=0
 for (( i=1; i<=$total; i++ ))
 do
- outputFile=$outputDir$i
- case $CMD in
-	print)
-		echo "bin/mlnsem run-condor $step $i $args $outputFile"
-		;;
-	submit)
-		echo "bin/mlnsem run-condor $step $i $args $outputFile" 
-		bin/mlnsem run-condor $step $i $args $outputFile
+	outputFile=$outputDir/out.$(( $i - 1 ))
+	case $CMD in
+	print | submit)
+		echo "bin/mlnsem run-condor $step $i $args"
 		;;
 	*)
-		b=$(tail $outputFile.out -n 5 | head -n 1)
+		b=$(tail $outputFile -n 5 | head -n 1)
 		len=$(expr length "$b")
 		len=$(expr $len - 2);
 		firstChar=$(expr substr "$b" 1 1)
@@ -158,50 +149,60 @@ do
 			errorCnt=$(($errorCnt + 1))
 		fi
 		;;
- esac
- case $CMD in
+	esac
+	case $CMD in
 	collect)
-		echo "$outputFile: $b"
+		#echo "$outputFile: $b"
 		if [[ "$i" == 1 ]]; then
 			echo "$outputFile: $b" > $outputDir/result
 		else
 			echo "$outputFile: $b" >> $outputDir/result
 		fi
 		collectBuffer="$collectBuffer $b"
-
 		;;
 	fix)
 		if [ "$b" == "ERROR" ]; then
-			echo "RESUBMIT bin/mlnsem run-condor $step $i $args $outputFile"
+			echo "RESUBMIT bin/mlnsem run-condor $step $i $args"
 			#bin/mlnsem run-condor $step $i $args $outputFile
-		else
-			echo "$i is ok"
+		# be silent when everything is okay.
+		#else
+		#	echo "$i is ok"
 		fi
 		;;
 	eval)
 		break
 		;;
- esac
-
-done	
+	esac
+done | case $CMD in
+	submit)
+		mkdir -p $outputDir
+		condargs --no-zero-pad -n $DS \
+			-o $outputDir \
+			--wait \
+			bash
+		;;
+	*)
+		cat -
+		;;
+esac
 
 case $CMD in 
 	collect)
-	echo "Errors found: $errorCnt"
-	echo  "Errors found: $errorCnt"  >> $outputDir/result
-	collectBuffer="[$collectBuffer]"
-	echo $collectBuffer >> $outputDir/result
-	;;
+		echo "Errors found: $errorCnt"
+		echo  "Errors found: $errorCnt"  >> $outputDir/result
+		collectBuffer="[$collectBuffer]"
+		echo $collectBuffer >> $outputDir/result
+		;;
 	fix)
-	echo "Errors resubmitted: $errorCnt"
-	;;
+		echo "Errors resubmitted: $errorCnt"
+		;;
 	eval)
 		if [ "$task" == "rte" ]; then
 			tail -n 1 $outputDir/result | bin/weka.sh classify $gs 4
 		else
 			tail -n 1 $outputDir/result | bin/weka.sh regress $gs
 		fi
-	;;
+		;;
 esac
 
 
